// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wymiana_Kart_TCG.Models;

namespace Wymiana_Kart_TCG.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200420212024_AddingShopingCartItem_2")]
    partial class AddingShopingCartItem_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wymiana_Kart_TCG.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CardCategoryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CardImgThumbnailUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardImgUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardLongDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardOtherDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CardPrice")
                        .HasColumnType("int");

                    b.Property<string>("CardShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCardAvailableToTrade")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCardDealOfTheWeek")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CardId");

                    b.HasIndex("CardCategoryCategoryId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CardImgThumbnailUrl = "https://www.lootpots.com/wp-content/uploads/2019/12/pokemon-sword-shield-666x374.jpg",
                            CardImgUrl = "https://imgix.ranker.com/user_node_img/36/700363/original/charizard-u21?w=650&q=50&fm=pjpg&fit=crop&crop=faces",
                            CardLongDescription = "Long description AlakazamAlakazamAlakazamAlakazamAlakazamAlakazamAlakazamAlakazamAlakazamAlakazamAlakazam",
                            CardName = "Alakazam",
                            CardPrice = 12,
                            CardShortDescription = "Our famous Alakazam Cards!",
                            CategoryId = 1,
                            IsCardAvailableToTrade = true,
                            IsCardDealOfTheWeek = true
                        },
                        new
                        {
                            CardId = 2,
                            CardImgThumbnailUrl = "https://www.lootpots.com/wp-content/uploads/2019/12/pokemon-sword-shield-666x374.jpg",
                            CardImgUrl = "https://imgix.ranker.com/user_node_img/36/700363/original/charizard-u21?w=650&q=50&fm=pjpg&fit=crop&crop=faces",
                            CardLongDescription = "Long description BlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoiseBlastoise",
                            CardName = "Blastoise",
                            CardPrice = 18,
                            CardShortDescription = "Our famous Blastoise Cards!",
                            CategoryId = 2,
                            IsCardAvailableToTrade = true,
                            IsCardDealOfTheWeek = false
                        },
                        new
                        {
                            CardId = 3,
                            CardImgThumbnailUrl = "https://www.lootpots.com/wp-content/uploads/2019/12/pokemon-sword-shield-666x374.jpg",
                            CardImgUrl = "https://imgix.ranker.com/user_node_img/36/700363/original/charizard-u21?w=650&q=50&fm=pjpg&fit=crop&crop=faces",
                            CardLongDescription = " Long description VenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaurVenusaur",
                            CardName = "Venusaur",
                            CardPrice = 18,
                            CardShortDescription = "Our famous Venusaur Cards!",
                            CategoryId = 2,
                            IsCardAvailableToTrade = true,
                            IsCardDealOfTheWeek = false
                        });
                });

            modelBuilder.Entity("Wymiana_Kart_TCG.Models.CardCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardCategoryName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("CardCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CardCategoryName = "Pokemon2"
                        },
                        new
                        {
                            CategoryId = 2,
                            CardCategoryName = "MTG2"
                        },
                        new
                        {
                            CategoryId = 3,
                            CardCategoryName = "Yugioh2"
                        });
                });

            modelBuilder.Entity("Wymiana_Kart_TCG.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("CardId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Wymiana_Kart_TCG.Models.Card", b =>
                {
                    b.HasOne("Wymiana_Kart_TCG.Models.CardCategory", "CardCategory")
                        .WithMany("Cards")
                        .HasForeignKey("CardCategoryCategoryId");
                });

            modelBuilder.Entity("Wymiana_Kart_TCG.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Wymiana_Kart_TCG.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");
                });
#pragma warning restore 612, 618
        }
    }
}
